# Generated by Django 3.1.2 on 2021-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Описание')),
                ('full_text', models.TextField(verbose_name='Текст блога')),
                ('date', models.DateTimeField(verbose_name='Время публикации')),
            ],
        ),
    ]
